apiVersion: v1
kind: Service
metadata:
  name: {{ include "trie.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "orihime.labels" . | indent 4 }}
    orihime/component: goo-trie
spec:
  type: ClusterIP
  ports:
    - port: 7081
      targetPort: 7081
      protocol: TCP
  selector:
    app.kubernetes.io/name: orihime-goo-trie
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dict.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "orihime.labels" . | indent 4 }}
    orihime/component: goo-dict
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: orihime-goo-dict
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mod.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "orihime.labels" . | indent 4 }}
    orihime/component: mod-goo
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: orihime-mod-goo
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "django.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "orihime.labels" . | indent 4 }}
    orihime/component: orihime-django
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: orihime-django
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
